//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generation date: 2015/10/20  18:07:45
namespace Gyb.Client.ODataProxy.Gyb.Server.Entities
{
    /// <summary>
    /// There are no comments for CourseSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("CourseSingle")]
    public partial class CourseSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Course>
    {
        /// <summary>
        /// Initialize a new CourseSingle object.
        /// </summary>
        public CourseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new CourseSingle object.
        /// </summary>
        public CourseSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new CourseSingle object.
        /// </summary>
        public CourseSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Course> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for CourseTutor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CourseTutor")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle CourseTutor
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CourseTutor == null))
                {
                    this._CourseTutor = new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle(this.Context, GetPath("CourseTutor"));
                }
                return this._CourseTutor;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle _CourseTutor;
        /// <summary>
        /// There are no comments for CourseSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CourseSubject")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle CourseSubject
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._CourseSubject == null))
                {
                    this._CourseSubject = new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle(this.Context, GetPath("CourseSubject"));
                }
                return this._CourseSubject;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle _CourseSubject;
        /// <summary>
        /// There are no comments for Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Enrollments")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> Enrollments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Enrollments == null))
                {
                    this._Enrollments = Context.CreateQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment>(GetPath("Enrollments"));
                }
                return this._Enrollments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> _Enrollments;
    }
    /// <summary>
    /// There are no comments for Course in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Course")]
    public partial class Course : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Course object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="duration">Initial value of Duration.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public static Course CreateCourse(int ID, double duration)
        {
            Course course = new Course();
            course.Id = ID;
            course.Duration = duration;
            return course;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Duration in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Duration")]
        public double Duration
        {
            get
            {
                return this._Duration;
            }
            set
            {
                this.OnDurationChanging(value);
                this._Duration = value;
                this.OnDurationChanged();
                this.OnPropertyChanged("Duration");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private double _Duration;
        partial void OnDurationChanging(double value);
        partial void OnDurationChanged();
        /// <summary>
        /// There are no comments for Property Description in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Description")]
        public string Description
        {
            get
            {
                return this._Description;
            }
            set
            {
                this.OnDescriptionChanging(value);
                this._Description = value;
                this.OnDescriptionChanged();
                this.OnPropertyChanged("Description");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _Description;
        partial void OnDescriptionChanging(string value);
        partial void OnDescriptionChanged();
        /// <summary>
        /// There are no comments for Property CourseTutor in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CourseTutor")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor CourseTutor
        {
            get
            {
                return this._CourseTutor;
            }
            set
            {
                this.OnCourseTutorChanging(value);
                this._CourseTutor = value;
                this.OnCourseTutorChanged();
                this.OnPropertyChanged("CourseTutor");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor _CourseTutor;
        partial void OnCourseTutorChanging(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor value);
        partial void OnCourseTutorChanged();
        /// <summary>
        /// There are no comments for Property CourseSubject in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("CourseSubject")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject CourseSubject
        {
            get
            {
                return this._CourseSubject;
            }
            set
            {
                this.OnCourseSubjectChanging(value);
                this._CourseSubject = value;
                this.OnCourseSubjectChanged();
                this.OnPropertyChanged("CourseSubject");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject _CourseSubject;
        partial void OnCourseSubjectChanging(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject value);
        partial void OnCourseSubjectChanged();
        /// <summary>
        /// There are no comments for Property Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Enrollments")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> Enrollments
        {
            get
            {
                return this._Enrollments;
            }
            set
            {
                this.OnEnrollmentsChanging(value);
                this._Enrollments = value;
                this.OnEnrollmentsChanged();
                this.OnPropertyChanged("Enrollments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> _Enrollments = new global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnEnrollmentsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> value);
        partial void OnEnrollmentsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for EnrollmentSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("EnrollmentSingle")]
    public partial class EnrollmentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Enrollment>
    {
        /// <summary>
        /// Initialize a new EnrollmentSingle object.
        /// </summary>
        public EnrollmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new EnrollmentSingle object.
        /// </summary>
        public EnrollmentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new EnrollmentSingle object.
        /// </summary>
        public EnrollmentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Enrollment> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Student")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle Student
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Student == null))
                {
                    this._Student = new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle(this.Context, GetPath("Student"));
                }
                return this._Student;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle _Student;
        /// <summary>
        /// There are no comments for Course in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Course")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle Course
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Course == null))
                {
                    this._Course = new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle(this.Context, GetPath("Course"));
                }
                return this._Course;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle _Course;
    }
    /// <summary>
    /// There are no comments for Enrollment in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Enrollment")]
    public partial class Enrollment : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Enrollment object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="enrollmentDate">Initial value of EnrollmentDate.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public static Enrollment CreateEnrollment(int ID, global::System.DateTimeOffset enrollmentDate)
        {
            Enrollment enrollment = new Enrollment();
            enrollment.Id = ID;
            enrollment.EnrollmentDate = enrollmentDate;
            return enrollment;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property EnrollmentDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("EnrollmentDate")]
        public global::System.DateTimeOffset EnrollmentDate
        {
            get
            {
                return this._EnrollmentDate;
            }
            set
            {
                this.OnEnrollmentDateChanging(value);
                this._EnrollmentDate = value;
                this.OnEnrollmentDateChanged();
                this.OnPropertyChanged("EnrollmentDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::System.DateTimeOffset _EnrollmentDate;
        partial void OnEnrollmentDateChanging(global::System.DateTimeOffset value);
        partial void OnEnrollmentDateChanged();
        /// <summary>
        /// There are no comments for Property Student in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Student")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student Student
        {
            get
            {
                return this._Student;
            }
            set
            {
                this.OnStudentChanging(value);
                this._Student = value;
                this.OnStudentChanged();
                this.OnPropertyChanged("Student");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student _Student;
        partial void OnStudentChanging(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student value);
        partial void OnStudentChanged();
        /// <summary>
        /// There are no comments for Property Course in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Course")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course Course
        {
            get
            {
                return this._Course;
            }
            set
            {
                this.OnCourseChanging(value);
                this._Course = value;
                this.OnCourseChanged();
                this.OnPropertyChanged("Course");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course _Course;
        partial void OnCourseChanging(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course value);
        partial void OnCourseChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for StudentSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("StudentSingle")]
    public partial class StudentSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Student>
    {
        /// <summary>
        /// Initialize a new StudentSingle object.
        /// </summary>
        public StudentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new StudentSingle object.
        /// </summary>
        public StudentSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new StudentSingle object.
        /// </summary>
        public StudentSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Student> query)
            : base(query) {}

        /// <summary>
        /// There are no comments for Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Enrollments")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> Enrollments
        {
            get
            {
                if (!this.IsComposable)
                {
                    throw new global::System.NotSupportedException("The previous function is not composable.");
                }
                if ((this._Enrollments == null))
                {
                    this._Enrollments = Context.CreateQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment>(GetPath("Enrollments"));
                }
                return this._Enrollments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> _Enrollments;
    }
    /// <summary>
    /// There are no comments for Student in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Student")]
    public partial class Student : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Student object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="gender">Initial value of Gender.</param>
        /// <param name="dateOfBirth">Initial value of DateOfBirth.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public static Student CreateStudent(int ID, global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender gender, global::System.DateTimeOffset dateOfBirth)
        {
            Student student = new Student();
            student.Id = ID;
            student.Gender = gender;
            student.DateOfBirth = dateOfBirth;
            return student;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Gender")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
                this.OnPropertyChanged("Gender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender _Gender;
        partial void OnGenderChanging(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender value);
        partial void OnGenderChanged();
        /// <summary>
        /// There are no comments for Property DateOfBirth in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("DateOfBirth")]
        public global::System.DateTimeOffset DateOfBirth
        {
            get
            {
                return this._DateOfBirth;
            }
            set
            {
                this.OnDateOfBirthChanging(value);
                this._DateOfBirth = value;
                this.OnDateOfBirthChanged();
                this.OnPropertyChanged("DateOfBirth");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::System.DateTimeOffset _DateOfBirth;
        partial void OnDateOfBirthChanging(global::System.DateTimeOffset value);
        partial void OnDateOfBirthChanged();
        /// <summary>
        /// There are no comments for Property RegistrationDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("RegistrationDate")]
        public global::System.Nullable<global::System.DateTimeOffset> RegistrationDate
        {
            get
            {
                return this._RegistrationDate;
            }
            set
            {
                this.OnRegistrationDateChanging(value);
                this._RegistrationDate = value;
                this.OnRegistrationDateChanged();
                this.OnPropertyChanged("RegistrationDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _RegistrationDate;
        partial void OnRegistrationDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnRegistrationDateChanged();
        /// <summary>
        /// There are no comments for Property LastLoginDate in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastLoginDate")]
        public global::System.Nullable<global::System.DateTimeOffset> LastLoginDate
        {
            get
            {
                return this._LastLoginDate;
            }
            set
            {
                this.OnLastLoginDateChanging(value);
                this._LastLoginDate = value;
                this.OnLastLoginDateChanged();
                this.OnPropertyChanged("LastLoginDate");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::System.Nullable<global::System.DateTimeOffset> _LastLoginDate;
        partial void OnLastLoginDateChanging(global::System.Nullable<global::System.DateTimeOffset> value);
        partial void OnLastLoginDateChanged();
        /// <summary>
        /// There are no comments for Property Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Enrollments")]
        public global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> Enrollments
        {
            get
            {
                return this._Enrollments;
            }
            set
            {
                this.OnEnrollmentsChanging(value);
                this._Enrollments = value;
                this.OnEnrollmentsChanged();
                this.OnPropertyChanged("Enrollments");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> _Enrollments = new global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment>(null, global::Microsoft.OData.Client.TrackingMode.None);
        partial void OnEnrollmentsChanging(global::Microsoft.OData.Client.DataServiceCollection<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> value);
        partial void OnEnrollmentsChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for SubjectSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("SubjectSingle")]
    public partial class SubjectSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Subject>
    {
        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new SubjectSingle object.
        /// </summary>
        public SubjectSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Subject> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Subject in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Subject")]
    public partial class Subject : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Subject object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public static Subject CreateSubject(int ID)
        {
            Subject subject = new Subject();
            subject.Id = ID;
            return subject;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Name")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for TutorSingle in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("TutorSingle")]
    public partial class TutorSingle : global::Microsoft.OData.Client.DataServiceQuerySingle<Tutor>
    {
        /// <summary>
        /// Initialize a new TutorSingle object.
        /// </summary>
        public TutorSingle(global::Microsoft.OData.Client.DataServiceContext context, string path)
            : base(context, path) {}

        /// <summary>
        /// Initialize a new TutorSingle object.
        /// </summary>
        public TutorSingle(global::Microsoft.OData.Client.DataServiceContext context, string path, bool isComposable)
            : base(context, path, isComposable) {}

        /// <summary>
        /// Initialize a new TutorSingle object.
        /// </summary>
        public TutorSingle(global::Microsoft.OData.Client.DataServiceQuerySingle<Tutor> query)
            : base(query) {}

    }
    /// <summary>
    /// There are no comments for Tutor in the schema.
    /// </summary>
    /// <KeyProperties>
    /// Id
    /// </KeyProperties>
    [global::Microsoft.OData.Client.Key("Id")]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Tutor")]
    public partial class Tutor : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Tutor object.
        /// </summary>
        /// <param name="ID">Initial value of Id.</param>
        /// <param name="gender">Initial value of Gender.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public static Tutor CreateTutor(int ID, global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender gender)
        {
            Tutor tutor = new Tutor();
            tutor.Id = ID;
            tutor.Gender = gender;
            return tutor;
        }
        /// <summary>
        /// There are no comments for Property Id in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Id")]
        public int Id
        {
            get
            {
                return this._Id;
            }
            set
            {
                this.OnIdChanging(value);
                this._Id = value;
                this.OnIdChanged();
                this.OnPropertyChanged("Id");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private int _Id;
        partial void OnIdChanging(int value);
        partial void OnIdChanged();
        /// <summary>
        /// There are no comments for Property Email in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Email")]
        public string Email
        {
            get
            {
                return this._Email;
            }
            set
            {
                this.OnEmailChanging(value);
                this._Email = value;
                this.OnEmailChanged();
                this.OnPropertyChanged("Email");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _Email;
        partial void OnEmailChanging(string value);
        partial void OnEmailChanged();
        /// <summary>
        /// There are no comments for Property UserName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("UserName")]
        public string UserName
        {
            get
            {
                return this._UserName;
            }
            set
            {
                this.OnUserNameChanging(value);
                this._UserName = value;
                this.OnUserNameChanged();
                this.OnPropertyChanged("UserName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _UserName;
        partial void OnUserNameChanging(string value);
        partial void OnUserNameChanged();
        /// <summary>
        /// There are no comments for Property Password in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Password")]
        public string Password
        {
            get
            {
                return this._Password;
            }
            set
            {
                this.OnPasswordChanging(value);
                this._Password = value;
                this.OnPasswordChanged();
                this.OnPropertyChanged("Password");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _Password;
        partial void OnPasswordChanging(string value);
        partial void OnPasswordChanged();
        /// <summary>
        /// There are no comments for Property FirstName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("FirstName")]
        public string FirstName
        {
            get
            {
                return this._FirstName;
            }
            set
            {
                this.OnFirstNameChanging(value);
                this._FirstName = value;
                this.OnFirstNameChanged();
                this.OnPropertyChanged("FirstName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _FirstName;
        partial void OnFirstNameChanging(string value);
        partial void OnFirstNameChanged();
        /// <summary>
        /// There are no comments for Property LastName in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("LastName")]
        public string LastName
        {
            get
            {
                return this._LastName;
            }
            set
            {
                this.OnLastNameChanging(value);
                this._LastName = value;
                this.OnLastNameChanged();
                this.OnPropertyChanged("LastName");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private string _LastName;
        partial void OnLastNameChanging(string value);
        partial void OnLastNameChanged();
        /// <summary>
        /// There are no comments for Property Gender in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Gender")]
        public global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender Gender
        {
            get
            {
                return this._Gender;
            }
            set
            {
                this.OnGenderChanging(value);
                this._Gender = value;
                this.OnGenderChanged();
                this.OnPropertyChanged("Gender");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender _Gender;
        partial void OnGenderChanging(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Gender value);
        partial void OnGenderChanged();
        /// <summary>
        /// This event is raised when the value of the property is changed
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        /// <summary>
        /// The value of the property is changed
        /// </summary>
        /// <param name="property">property name</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for Gender in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Gender")]
    public enum Gender
    {
        [global::Microsoft.OData.Client.OriginalNameAttribute("Male")]
        Male = 0,
        [global::Microsoft.OData.Client.OriginalNameAttribute("Female")]
        Female = 1
    }
    /// <summary>
    /// Class containing all extension methods
    /// </summary>
    public static class ExtensionMethods
    {
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.CourseSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.EnrollmentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.EnrollmentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.EnrollmentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.EnrollmentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.EnrollmentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.EnrollmentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.StudentSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.SubjectSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="keys">dictionary with the names and values of keys</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor> source, global::System.Collections.Generic.Dictionary<string, object> keys)
        {
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
        /// <summary>
        /// Get an entity of type global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor as global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle specified by key from an entity set
        /// </summary>
        /// <param name="source">source entity set</param>
        /// <param name="id">The value of id</param>
        public static global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle ByKey(this global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor> source,
            int id)
        {
            global::System.Collections.Generic.Dictionary<string, object> keys = new global::System.Collections.Generic.Dictionary<string, object>
            {
                { "Id", id }
            };
            return new global::Gyb.Client.ODataProxy.Gyb.Server.Entities.TutorSingle(source.Context, source.GetKeyPath(global::Microsoft.OData.Client.Serializer.GetKeyString(source.Context, keys)));
        }
    }
}
namespace Gyb.Client.ODataProxy.Default
{
    /// <summary>
    /// There are no comments for Container in the schema.
    /// </summary>
    [global::Microsoft.OData.Client.OriginalNameAttribute("Container")]
    public partial class Container : global::Microsoft.OData.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new Container object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public Container(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::Microsoft.OData.Client.ODataProtocolVersion.V4)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
            this.Format.LoadServiceModel = GeneratedEdmModel.GetInstance;
            this.Format.UseJson();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            global::System.Type resolvedType = this.DefaultResolveType(typeName, "Gyb.Server.Entities", "Gyb.Client.ODataProxy.Gyb.Server.Entities");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            resolvedType = this.DefaultResolveType(typeName, "Default", "Gyb.Client.ODataProxy.Default");
            if ((resolvedType != null))
            {
                return resolvedType;
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            global::Microsoft.OData.Client.OriginalNameAttribute originalNameAttribute = (global::Microsoft.OData.Client.OriginalNameAttribute)global::System.Linq.Enumerable.SingleOrDefault(global::Microsoft.OData.Client.Utility.GetCustomAttributes(clientType, typeof(global::Microsoft.OData.Client.OriginalNameAttribute), true));
            if (clientType.Namespace.Equals("Gyb.Client.ODataProxy.Gyb.Server.Entities", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Gyb.Server.Entities.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Gyb.Server.Entities.", clientType.Name);
            }
            if (clientType.Namespace.Equals("Gyb.Client.ODataProxy.Default", global::System.StringComparison.Ordinal))
            {
                if (originalNameAttribute != null)
                {
                    return string.Concat("Default.", originalNameAttribute.OriginalName);
                }
                return string.Concat("Default.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Courses")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course> Courses
        {
            get
            {
                if ((this._Courses == null))
                {
                    this._Courses = base.CreateQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course>("Courses");
                }
                return this._Courses;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course> _Courses;
        /// <summary>
        /// There are no comments for Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Enrollments")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> Enrollments
        {
            get
            {
                if ((this._Enrollments == null))
                {
                    this._Enrollments = base.CreateQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment>("Enrollments");
                }
                return this._Enrollments;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment> _Enrollments;
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Students")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student> Students
        {
            get
            {
                if ((this._Students == null))
                {
                    this._Students = base.CreateQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student>("Students");
                }
                return this._Students;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student> _Students;
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Subjects")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject> Subjects
        {
            get
            {
                if ((this._Subjects == null))
                {
                    this._Subjects = base.CreateQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject>("Subjects");
                }
                return this._Subjects;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject> _Subjects;
        /// <summary>
        /// There are no comments for Tutors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        [global::Microsoft.OData.Client.OriginalNameAttribute("Tutors")]
        public global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor> Tutors
        {
            get
            {
                if ((this._Tutors == null))
                {
                    this._Tutors = base.CreateQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor>("Tutors");
                }
                return this._Tutors;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private global::Microsoft.OData.Client.DataServiceQuery<global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor> _Tutors;
        /// <summary>
        /// There are no comments for Courses in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public void AddToCourses(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Course course)
        {
            base.AddObject("Courses", course);
        }
        /// <summary>
        /// There are no comments for Enrollments in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public void AddToEnrollments(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Enrollment enrollment)
        {
            base.AddObject("Enrollments", enrollment);
        }
        /// <summary>
        /// There are no comments for Students in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public void AddToStudents(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Student student)
        {
            base.AddObject("Students", student);
        }
        /// <summary>
        /// There are no comments for Subjects in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public void AddToSubjects(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Subject subject)
        {
            base.AddObject("Subjects", subject);
        }
        /// <summary>
        /// There are no comments for Tutors in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        public void AddToTutors(global::Gyb.Client.ODataProxy.Gyb.Server.Entities.Tutor tutor)
        {
            base.AddObject("Tutors", tutor);
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
        private abstract class GeneratedEdmModel
        {
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
            private static global::Microsoft.OData.Edm.IEdmModel ParsedModel = LoadModelFromString();
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
            private const string Edmx = @"<edmx:Edmx Version=""4.0"" xmlns:edmx=""http://docs.oasis-open.org/odata/ns/edmx"">
  <edmx:DataServices>
    <Schema Namespace=""Gyb.Server.Entities"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityType Name=""Course"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
        <Property Name=""Duration"" Type=""Edm.Double"" Nullable=""false"" />
        <Property Name=""Description"" Type=""Edm.String"" />
        <NavigationProperty Name=""CourseTutor"" Type=""Gyb.Server.Entities.Tutor"" />
        <NavigationProperty Name=""CourseSubject"" Type=""Gyb.Server.Entities.Subject"" />
        <NavigationProperty Name=""Enrollments"" Type=""Collection(Gyb.Server.Entities.Enrollment)"" />
      </EntityType>
      <EntityType Name=""Enrollment"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""EnrollmentDate"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <NavigationProperty Name=""Student"" Type=""Gyb.Server.Entities.Student"" />
        <NavigationProperty Name=""Course"" Type=""Gyb.Server.Entities.Course"" />
      </EntityType>
      <EntityType Name=""Student"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""UserName"" Type=""Edm.String"" />
        <Property Name=""Password"" Type=""Edm.String"" />
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""LastName"" Type=""Edm.String"" />
        <Property Name=""Gender"" Type=""Gyb.Server.Entities.Gender"" Nullable=""false"" />
        <Property Name=""DateOfBirth"" Type=""Edm.DateTimeOffset"" Nullable=""false"" />
        <Property Name=""RegistrationDate"" Type=""Edm.DateTimeOffset"" />
        <Property Name=""LastLoginDate"" Type=""Edm.DateTimeOffset"" />
        <NavigationProperty Name=""Enrollments"" Type=""Collection(Gyb.Server.Entities.Enrollment)"" />
      </EntityType>
      <EntityType Name=""Subject"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Name"" Type=""Edm.String"" />
      </EntityType>
      <EntityType Name=""Tutor"">
        <Key>
          <PropertyRef Name=""Id"" />
        </Key>
        <Property Name=""Id"" Type=""Edm.Int32"" Nullable=""false"" />
        <Property Name=""Email"" Type=""Edm.String"" />
        <Property Name=""UserName"" Type=""Edm.String"" />
        <Property Name=""Password"" Type=""Edm.String"" />
        <Property Name=""FirstName"" Type=""Edm.String"" />
        <Property Name=""LastName"" Type=""Edm.String"" />
        <Property Name=""Gender"" Type=""Gyb.Server.Entities.Gender"" Nullable=""false"" />
      </EntityType>
      <EnumType Name=""Gender"">
        <Member Name=""Male"" Value=""0"" />
        <Member Name=""Female"" Value=""1"" />
      </EnumType>
    </Schema>
    <Schema Namespace=""Default"" xmlns=""http://docs.oasis-open.org/odata/ns/edm"">
      <EntityContainer Name=""Container"">
        <EntitySet Name=""Courses"" EntityType=""Gyb.Server.Entities.Course"">
          <NavigationPropertyBinding Path=""CourseTutor"" Target=""Tutors"" />
          <NavigationPropertyBinding Path=""CourseSubject"" Target=""Subjects"" />
          <NavigationPropertyBinding Path=""Enrollments"" Target=""Enrollments"" />
        </EntitySet>
        <EntitySet Name=""Enrollments"" EntityType=""Gyb.Server.Entities.Enrollment"">
          <NavigationPropertyBinding Path=""Student"" Target=""Students"" />
          <NavigationPropertyBinding Path=""Course"" Target=""Courses"" />
        </EntitySet>
        <EntitySet Name=""Students"" EntityType=""Gyb.Server.Entities.Student"">
          <NavigationPropertyBinding Path=""Enrollments"" Target=""Enrollments"" />
        </EntitySet>
        <EntitySet Name=""Subjects"" EntityType=""Gyb.Server.Entities.Subject"" />
        <EntitySet Name=""Tutors"" EntityType=""Gyb.Server.Entities.Tutor"" />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>";
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
            public static global::Microsoft.OData.Edm.IEdmModel GetInstance()
            {
                return ParsedModel;
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
            private static global::Microsoft.OData.Edm.IEdmModel LoadModelFromString()
            {
                global::System.Xml.XmlReader reader = CreateXmlReader(Edmx);
                try
                {
                    return global::Microsoft.OData.Edm.Csdl.EdmxReader.Parse(reader);
                }
                finally
                {
                    ((global::System.IDisposable)(reader)).Dispose();
                }
            }
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.OData.Client.T4", "2.3.0")]
            private static global::System.Xml.XmlReader CreateXmlReader(string edmxToParse)
            {
                return global::System.Xml.XmlReader.Create(new global::System.IO.StringReader(edmxToParse));
            }
        }
    }
}
